fieldLayouts:
  963e86ab-c290-4726-90bc-b83df5700737:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 93c8e28c-aade-4d91-b2fb-5396bfe36d52
            warning: null
            width: 100
          -
            fieldUid: d496ac5c-04e4-49f3-94e5-ca565c4b2812 # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99fa5380-ae59-4bb7-82f2-8e7c3c709fdd
            warning: null
            width: 100
        name: Content
        uid: 3b05a6a1-da14-45c3-a24b-8776b3a0022f
handle: home
hasTitleField: false
name: Home
section: 5544e175-a6da-429c-b0d7-a4bbe157672d # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
