fieldLayouts:
  ce40c337-d025-4e7d-9f1e-9478cdee8504:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5d770c37-45c7-4f7b-9a1d-6abfca533d56
            warning: null
            width: 100
        name: Content
        uid: 6734d6f9-6e8f-4d61-9ae1-75addb51fe34
handle: portfolio
hasTitleField: false
name: Portfolio
section: 0856402b-c53b-4ed4-850a-456f6d37df97 # Portfolio
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
