defaultPlacement: end
enableVersioning: true
handle: portfolio
name: Portfolio
propagationMethod: all
siteSettings:
  24f2dcb8-63d1-4381-88c2-6a00dc080773: # zazreco
    enabledByDefault: true
    hasUrls: true
    template: portfolio/index
    uriFormat: portfolio
type: single
